// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnc-niRE7M449eeNhfg0760eds8t9Tbnw',
    appId: '1:767071743798:web:9efd6226d6d7c08523cd97',
    messagingSenderId: '767071743798',
    projectId: 'urban-556e3',
    authDomain: 'urban-556e3.firebaseapp.com',
    storageBucket: 'urban-556e3.firebasestorage.app',
    measurementId: 'G-FN1Q25F8SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASGxnLaIWbU6sVDGfur1sYnwIheT-y4-0',
    appId: '1:767071743798:android:739efb4f079003d423cd97',
    messagingSenderId: '767071743798',
    projectId: 'urban-556e3',
    storageBucket: 'urban-556e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yfQ8XIha2DIJIMbxVHY0CGEVuzO9Jx4',
    appId: '1:767071743798:ios:f7efb2e919157ee723cd97',
    messagingSenderId: '767071743798',
    projectId: 'urban-556e3',
    storageBucket: 'urban-556e3.firebasestorage.app',
    iosBundleId: 'com.example.urbanflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5yfQ8XIha2DIJIMbxVHY0CGEVuzO9Jx4',
    appId: '1:767071743798:ios:f7efb2e919157ee723cd97',
    messagingSenderId: '767071743798',
    projectId: 'urban-556e3',
    storageBucket: 'urban-556e3.firebasestorage.app',
    iosBundleId: 'com.example.urbanflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnc-niRE7M449eeNhfg0760eds8t9Tbnw',
    appId: '1:767071743798:web:fb7755d2d9cd3a0923cd97',
    messagingSenderId: '767071743798',
    projectId: 'urban-556e3',
    authDomain: 'urban-556e3.firebaseapp.com',
    storageBucket: 'urban-556e3.firebasestorage.app',
    measurementId: 'G-JK56ETXTG1',
  );
}
